apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  HOST: {{ .Values.mysql.host | b64enc }}
  PORT: {{ .Values.mysql.port | b64enc }}
  DATABASE: {{ .Values.mysql.database | b64enc }}
  USERNAME: {{ .Values.mysql.username | b64enc }}
  PASSWORD: {{ .Values.mysql.rootPassword | b64enc }}

